export { default as Home } from './home/Home'
export { default as NotFound } from './notFound/NotFound'
export { default as Register } from './auth/Register'
export { default as Login } from './auth/Login'
export { default as ResetPassword } from './auth/ResetPassword'